CREATE DATABASE userDB;

USE userDB;

DELIMITER $$

CREATE FUNCTION UUID_TO_BIN(uuid CHAR(36))
RETURNS BINARY(16)
DETERMINISTIC
BEGIN
    RETURN UNHEX(REPLACE(uuid, '-', ''));
END $$

DELIMITER ;

CREATE TABLE User (
    accountID BINARY(16) PRIMARY KEY,
    DNI VARCHAR(8) NOT NULL,
    password VARCHAR(255) NOT NULL
);